name: CI
on: workflow_dispatch
## XXX: manually CI trigger for now, because we only get 200 mins of MacOS CI time per month!
## on:
##   push:
##     branches: [main]
##   pull_request:
##     branches: [main]

jobs:
  macos_big_sur:
    runs-on: macos-11

    strategy:
      matrix:
        xcode:
          - "13.2" # Swift 5.5

    name: "macOS Big Sur (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build All Apps
        run: |
          sqlite3 "~/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 2, 1, 0, 'com.apple.imageevents')
          make allapps
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  macos_catalina:
    runs-on: macos-10.15

    strategy:
      matrix:
        xcode:
          - "12" # Swift 5.3

    name: "macOS Catalina (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build All Apps
        run: |
          sqlite3 "~/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 2, 1, 0, 'com.apple.imageevents')
          make allapps
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
